"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main_ui.py']
DATA_FILES = ['金融帝国博弈.txt', '人类简史.txt', '从林肯到奥巴马时代.txt','债务危机.txt',
 '早晨从中午开始.txt','周杰伦.txt','一只特立独行的猪.txt','思考快与慢.txt','原则.txt',
 '阳谋高手.txt','我们为什么会分手.txt','README.txt','自定义.txt',"log.csv"]

OPTIONS = {"packages":["PySimpleGUI","random","re","os"], 'iconfile':'mind.icns',}
# OPTIONS = {}

setup(
    app=APP,
    name=u"记忆训练助手Mac版",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
